apiVersion: ceph.rook.io/v1
kind: CephFilesystem
metadata:
  name: myfs
  namespace: rook-ceph
spec:
  metadataPool:
    replicated:
      size: {{ replica_number }}
      requireSafeReplicaSize: false
  dataPools:
    - failureDomain: osd
      replicated:
        size: {{ replica_number }}
        requireSafeReplicaSize: false
      compressionMode: none
  preservePoolsOnDelete: false
  metadataServer:
    activeCount: 1
    activeStandby: true

