- hosts: bastion
  vars:
    ics_version_hint: "{{ lookup('env','GI_ICS_VERSION') }}"
    ics_versions: [ "3.7.4","3.8.1","3.9.1","3.10.0","3.11.0","3.12.1","3.13.0" ]
    ics_cases: [ "ibm-cp-common-services-1.3.4.tgz","ibm-cp-common-services-1.4.1.tgz","ibm-cp-common-services-1.5.1.tgz","ibm-cp-common-services-1.6.0.tgz","ibm-cp-common-services-1.7.0.tgz","ibm-cp-common-services-1.8.1.tgz","ibm-cp-common-services-1.9.0.tgz" ]
    ics_operands: "{{ lookup('env','GI_ICS_OPERANDS').split(',') }}"
    ics_admin_password: "{{ lookup('env','GI_ICSADMIN_PWD') }}"
    ocadmin:  "{{ lookup('env','GI_OCADMIN') }}"
    ocadmin_password:  "{{ lookup('env','GI_OCADMIN_PWD') }}"
    domain:  "{{ lookup('env','GI_DOMAIN') }}"


  tasks:
  - name: Check other configuration parameters
    fail: msg="Variable {{ item.name }} is not set"
    when: item.value == ""
    loop:
      - { name: "GI_ICS_VERSION", value: "{{ ics_version_hint }}" }
      - { name: "GI_ICS_OPERANDS", value: "{{ ics_operands }}" }
      - { name: "GI_ICSADMIN_PWD", value: "{{ ics_admin_password }}" }

  - name: Get ICS operator name
    shell:
      cmd: oc get  ClusterServiceVersion -n ibm-common-services -o name|grep ibm-common-service-operator
    register: ics_operator

  - name: Delete ICS operator
    shell:
      cmd: "oc delete {{ ics_operator.stdout }} -n ibm-common-services"

  - name: Delete common-service project
    shell:
      cmd: oc delete project common-service

  - name: Delete operand requests
    shell:
      cmd: 'for operator in `oc get OperandRequest -n ibm-common-services -o name`; do oc delete $operator -n ibm-common-services;done'
    ignore_errors: yes #some operands remove other so the list is dynamic

  - name: Login to OCP after ICS Authorization removal
    shell:
      cmd: "oc login https://api.{{ domain }}:6443 -u {{ ocadmin }} -p {{ ocadmin_password }} --insecure-skip-tls-verify=true"
    register: login_status
    until: "login_status.stdout == \"0\""
    retries: 150
    delay: 3


  - name: Delete operand configs
    shell:
      cmd: 'for config in `oc get OperandConfig -n ibm-common-services -o name`; do oc delete $config -n ibm-common-services;done'

  - name: Delete operand registries
    shell:
      cmd: 'for registry in `oc get OperandRegistry -n ibm-common-services -o name`; do oc delete $registry -n ibm-common-services;done'
   
  - name: Delete operand namespacescopes
    shell:
      cmd: 'for nscope in `oc get NamespaceScope -n ibm-common-services -o name`; do oc delete $nscope -n ibm-common-services;done'

  - name: Delete remaining ICS operators
    shell:
      cmd: 'for operator in `oc get  ClusterServiceVersion -n ibm-common-services -o name`;do oc delete $operator -n ibm-common-services;done'

  - name: Delete ibm-common-services project
    shell:
      cmd: oc delete project ibm-common-services

  - name: Delete remaining objects
    shell:
      cmd: "{{ item }}"
    with_items:
      - 'oc -n kube-system delete secret icp-metering-api-secret --ignore-not-found'
      - 'oc -n kube-public delete configmap ibmcloud-cluster-info --ignore-not-found'
      - 'oc -n kube-public delete secret ibmcloud-cluster-ca-cert --ignore-not-found'
      - 'oc delete ValidatingWebhookConfiguration cert-manager-webhook ibm-cs-ns-mapping-webhook-configuration --ignore-not-found'
      - 'oc delete MutatingWebhookConfiguration cert-manager-webhook ibm-common-service-webhook-configuration ibm-operandrequest-webhook-configuration namespace-admission-config --ignore-not-found'
      - 'oc delete namespace services'
      - 'oc delete nss --all'

  - name: Delete ICS crd's
    shell:
      cmd: 'for crd in `oc get crd -o name| grep ibm.com`;do oc delete $crd;done'

  - name: Delete ICS catalog
    shell:
      cmd: 'oc delete -f ../gi-temp/ics_catalog.yaml'

  - debug:
        msg:
          - "ICS uninstalled with success."
