- hosts: bastion
  vars:
    ics_version_hint: "{{ lookup('env','GI_ICS_VERSION') }}"
    ics_operands: "{{ lookup('env','GI_ICS_OPERANDS').split(',') }}"
    ics_admin_password: "{{ lookup('env','GI_ICSADMIN_PWD') }}"
    ocadmin:  "{{ lookup('env','GI_OCADMIN') }}"
    ocadmin_password:  "{{ lookup('env','GI_OCADMIN_PWD') }}"
    domain:  "{{ lookup('env','GI_DOMAIN') }}"
    gi_version_index:  "{{ lookup('env','GI_VERSION') }}"
    gi_namespace: "{{ lookup('env', 'GI_NAMESPACE_GI') }}"

  tasks:
  - name: Check other configuration parameters
    fail: msg="Variable {{ item.name }} is not set"
    when: item.value == ""
    loop:
      - { name: "GI_ICS_VERSION", value: "{{ ics_version_hint }}" }
      - { name: "GI_ICS_OPERANDS", value: "{{ ics_operands }}" }
      - { name: "GI_ICSADMIN_PWD", value: "{{ ics_admin_password }}" }
      - { name: "GI_VERSION", value: "{{ gi_version_index }}" }
      - { name: "GI_NAMESPACE_GI", value: "{{ gi_namespace }}" }

  - name: Set GI installation variables
    set_fact:
      gi_case_inventory_setup: "install"
      gi_case_archive: "{{ 'ibm-guardium-insights-2.0.0.tgz' if gi_version_index == '0' else 'ibm-guardium-insights-2.0.1.tgz' if gi_version_index == '1' else 'ibm-guardium-insights-2.0.2.tgz' }}"
      offline_inventory: "gi_offline"
      gi_version: "{{ '3.0.0' if gi_version_index == '0' else '3.0.1' if gi_version_index == '1' else '3.0.2' }}"

  - name: Delete GI operator instance
    shell:
      cmd: "oc delete guardiuminisghts {{ gi_namespace }} -n {{ gi_namespace }}||true "

  - name: Wait for cleanup
    pause:
      minutes: 2

  - name: Delete tenant sniffer instance
    shell:
      cmd: "oc delete tenantminisnif --all||true "

  - name: Wait for API server successful reconfiguration
    shell:
      cmd: "oc get pods -n gi --no-headers|grep -v Running|wc -l"
    register: gi_pods
    until: "gi_pods.stdout == \"0\""
    retries: 20
    delay: 20

  - meta: end_play

  - name: Delete ICS operator
    shell:
      cmd: "oc delete {{ ics_operator.stdout }} -n ibm-common-services"

  - name: Delete common-service project
    shell:
      cmd: oc delete project common-service

  - name: Delete operand common-service
    shell:
      cmd: 'oc delete operandrequest.operator.ibm.com/common-service -n ibm-common-services'

  - name: Wait for operands removal
    pause:
      minutes: 5

  - name: Login to OCP after ICS API removal
    shell:
      cmd: "oc login https://api.{{ domain }}:6443 -u {{ ocadmin }} -p {{ ocadmin_password }} --insecure-skip-tls-verify=true"
    register: login_status
    until: "login_status.stderr == \"\""
    retries: 5 
    delay: 3

  - name: Check that operands are removed 
    shell:
      cmd: 'oc get OperandRequest -n ibm-common-services -o name|wc -l'
    register: operands_number
    until: "operands_number.stdout == \"0\""
    retries: 30
    delay: 30

  - name: Delete operand configs
    shell:
      cmd: 'for config in `oc get OperandConfig -n ibm-common-services -o name`; do oc delete $config -n ibm-common-services;done'

  - name: Delete operand registries
    shell:
      cmd: 'for registry in `oc get OperandRegistry -n ibm-common-services -o name`; do oc delete $registry -n ibm-common-services;done'
   
  - name: Delete operand namespacescopes
    shell:
      cmd: 'for nscope in `oc get NamespaceScope -n ibm-common-services -o name`; do oc delete $nscope -n ibm-common-services;done'

  - name: Delete remaining ICS operators
    shell:
      cmd: 'for operator in `oc get  ClusterServiceVersion -n ibm-common-services -o name`;do oc delete $operator -n ibm-common-services;done'

  - name: Delete ibm-common-services project
    shell:
      cmd: oc delete project ibm-common-services

  - name: Delete remaining objects
    shell:
      cmd: "{{ item }}"
    with_items:
      - 'oc -n kube-system delete secret icp-metering-api-secret --ignore-not-found'
      - 'oc -n kube-public delete configmap ibmcloud-cluster-info --ignore-not-found'
      - 'oc -n kube-public delete secret ibmcloud-cluster-ca-cert --ignore-not-found'
      - 'oc delete ValidatingWebhookConfiguration cert-manager-webhook ibm-cs-ns-mapping-webhook-configuration --ignore-not-found'
      - 'oc delete MutatingWebhookConfiguration cert-manager-webhook ibm-common-service-webhook-configuration ibm-operandrequest-webhook-configuration namespace-admission-config --ignore-not-found'
      - 'oc delete namespace services'
      - 'oc delete nss --all'

  - name: Delete ICS crd's
    shell:
      cmd: 'for crd in `oc get crd -o name| grep ibm.com`;do oc delete $crd;done'

  - name: Delete ICS catalog
    shell:
      cmd: 'oc delete -f ../gi-temp/ics_catalog.yaml'

  - name: Delete ICS installation files
    file:
      path: "{{ item }}"
      state: absent
    with_items:
      - '../gi-temp/cloudctl-linux-amd64.tar.gz'
      - '../gi-temp/ics_operands.yaml'
      - '../gi-temp/ics_catalog.yaml'

  - debug:
        msg:
          - "ICS uninstalled with success."
