- name: Accept certicates
  shell: oc get csr -o go-template='{{range .items}}{{if not .status}}{{.metadata.name}}{{"\n"}}{{end}}{{end}}' | xargs oc adm certificate approve

- name: Debug
  msg: "{{ worker_ip|length + node_ip|length }}"

