- hosts: bastion
  vars:
    temp_dir: "../gi-temp"
    internet_type:  "{{ lookup('env','GI_INTERNET_ACCESS') }}"
    domain:  "{{ lookup('env','GI_DOMAIN') }}"


  tasks:
    - name: Check standard configuration parameters
      fail: msg="Variable {{ item.name }} is not set"
      when: item.value == ""
      loop:
        - { name: "GI_INTERNET_ACCESS", value: "{{ internet_type }}" }
        - { name: "GI_DOMAIN", value: "{{ domain }}" }

          
    - name: Setup bastion
      include: setup_bastion.yaml
